import { Link } from 'react-router-dom'
import { useAuth } from '../../app/providers/authContext'
import { canManageUsers } from '../../shared/permissions/permissions'
import { canManageHrConfiguration } from '../../shared/permissions/permissions'
import { roleLabel } from '../../shared/constants/roles'
import Icon from '../../shared/components/Icon/Icon'

export default function HomePage() {
  const { user } = useAuth()
  const actions = [
    ...(canManageUsers(user) ? [{ to: '/users/new', icon: 'users', title: 'Create user', description: 'Set up secure access for a teammate.' }] : []),
    ...(canManageHrConfiguration(user) ? [{ to: '/departments/new', icon: 'departments', title: 'Add department', description: 'Organize your workforce structure.' }, { to: '/working-schedules/new', icon: 'schedules', title: 'Create schedule', description: 'Define expected working hours.' }] : []),
  ]
  return <section className="dashboard"><header className="dashboard-hero"><div><p className="eyebrow">People operations</p><h1>Good to see you, {user.firstName}.</h1><p>Here is a focused view of your PeoplePay360 workspace.</p></div><div className="hero-role"><span className="status-dot" />{roleLabel(user.role)}</div></header><div className="metric-grid"><article className="metric-card"><span className="metric-icon"><Icon name="dashboard" /></span><div><small>Workspace</small><strong>Connected</strong><p>Your account is securely active.</p></div></article><article className="metric-card"><span className="metric-icon metric-icon--violet"><Icon name="users" /></span><div><small>Your access</small><strong>{roleLabel(user.role)}</strong><p>Tools are tailored to your role.</p></div></article><article className="metric-card"><span className="metric-icon metric-icon--green"><Icon name="security" /></span><div><small>Account security</small><strong>Protected</strong><p>Manage password and session settings.</p></div></article></div><div className="dashboard-grid"><section className="dashboard-panel dashboard-panel--wide"><div className="panel-heading"><div><p className="eyebrow">Get started</p><h2>Quick actions</h2></div></div>{actions.length ? <div className="quick-actions">{actions.map((action) => <Link key={action.to} className="quick-action" to={action.to}><span className="feature-icon"><Icon name={action.icon} /></span><span><strong>{action.title}</strong><small>{action.description}</small></span><Icon name="arrow" size={18} /></Link>)}</div> : <div className="empty-dashboard"><span className="feature-icon"><Icon name="dashboard" /></span><div><strong>Your workspace is ready</strong><p>Use the navigation to access the tools available to your role.</p></div></div>}</section><aside className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">Status</p><h2>Platform updates</h2></div></div><div className="activity-item"><span className="activity-dot" /><div><strong>Secure session enabled</strong><p>Your session and role permissions are active.</p></div></div><div className="activity-item"><span className="activity-dot activity-dot--muted" /><div><strong>More insights coming soon</strong><p>Payroll and people metrics will appear when those services are available.</p></div></div></aside></div></section>
}
