import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import employeesApi from '../../employees/api/employeesApi'
import { downloadPayslipPdf } from '../../payslips/api/payslipApi'
import salaryConfigApi from '../../salaryConfig/api/salaryConfigApi'
import payrunApi from '../api/payrunApi'
import { employeeIssueLabel, formatDate, formatMoney, recordId, structureLabel } from '../payrollUiUtils'

export default function PayrunProcessingPage() {
  const { id } = useParams(); const [payrun, setPayrun] = useState(null); const [payslips, setPayslips] = useState([]); const [structures, setStructures] = useState([]); const [employees, setEmployees] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [delivery, setDelivery] = useState(null)
  const refresh = async () => { const [run, slips, structureResult, employeeResult] = await Promise.all([payrunApi.get(id), payrunApi.payslips(id), salaryConfigApi.listStructures({ page: 1, limit: 100 }), employeesApi.list({ page: 1, limit: 100 })]); setPayrun(run); setPayslips(slips.data); setStructures(structureResult.data); setEmployees(employeeResult.data) }
  useEffect(() => { let active = true; Promise.all([payrunApi.get(id), payrunApi.payslips(id), salaryConfigApi.listStructures({ page: 1, limit: 100 }), employeesApi.list({ page: 1, limit: 100 })]).then(([run, slips, structureResult, employeeResult]) => { if (active) { setPayrun(run); setPayslips(slips.data); setStructures(structureResult.data); setEmployees(employeeResult.data); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [id])
  const action = async (name) => { setBusy(name); setError(''); if (name !== 'sendPayslips') setDelivery(null); try { const result = await payrunApi[name](id); if (name === 'sendPayslips') setDelivery(result); await refresh() } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const pdf = async (payslipId) => { setBusy(`pdf-${payslipId}`); setError(''); try { await downloadPayslipPdf(payslipId) } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const columns = useMemo(() => [{ key: 'employee', label: 'Employee', render: (row) => row.employeeSnapshot?.name || employeeIssueLabel(row.employee, employees) }, { key: 'worked', label: 'Worked Days', render: (row) => row.workedDays }, { key: 'gross', label: 'Gross', render: (row) => formatMoney(row.grossSalary) }, { key: 'deductions', label: 'Deductions', render: (row) => formatMoney(row.totalDeductions) }, { key: 'net', label: 'Net', render: (row) => <strong>{formatMoney(row.netSalary)}</strong> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'warnings', label: 'Warnings', render: (row) => row.warnings?.length || 0 }, { key: 'action', label: '', render: (row) => <div className="row-actions"><Link className="button-link" to={`/payroll/payslips/${row.id}`}>View</Link>{['VALIDATED', 'PAID'].includes(row.status) && <button className="button-link" disabled={busy === `pdf-${row.id}`} onClick={() => pdf(row.id)}>PDF</button>}</div> }], [busy, employees])
  if (loading) return <LoadingState label="Loading Payrun..." />
  if (!payrun) return <section className="center-message"><h1>Unable to load Payrun</h1><p>{error}</p><Link className="button" to="/payroll/payruns">Back</Link></section>
  const issues = payrun.warnings || []
  return <><ErrorBanner message={error} /><header className="page-header"><div><p className="eyebrow">Payrun Processing</p><h1>{payrun.name}</h1><div className="badge-row"><StatusBadge value={payrun.status} /><span>{structureLabel(payrun.salaryStructure, structures)}</span></div><p>{formatDate(payrun.periodStart)} - {formatDate(payrun.periodEnd)} · {payrun.employees?.length || 0} employees</p></div><div className="header-actions"><Link className="button button--secondary" to="/payroll/payruns">Back</Link>{payrun.status === 'DRAFT' && <button className="button" disabled={Boolean(busy)} onClick={() => action('compute')}>{busy === 'compute' ? 'Computing...' : 'Compute'}</button>}{payrun.status === 'COMPUTED' && <><button className="button button--secondary" disabled={Boolean(busy)} onClick={() => action('compute')}>Compute Again</button><button className="button" disabled={Boolean(busy)} onClick={() => action('validate')}>{busy === 'validate' ? 'Validating...' : 'Validate'}</button></>}{payrun.status === 'VALIDATED' && <button className="button" disabled={Boolean(busy)} onClick={() => action('markPaid')}>{busy === 'markPaid' ? 'Updating...' : 'Mark Paid'}</button>}{payrun.status === 'PAID' && <button className="button" disabled={Boolean(busy)} onClick={() => action('sendPayslips')}>{busy === 'sendPayslips' ? 'Sending...' : 'Send Payslips'}</button>}</div></header>
    <section className="panel payroll-issues"><div className="section-toolbar"><div><h2>Warnings and blocking issues ({issues.length})</h2><p>Blocking items prevent validation; warnings remain informational.</p></div></div>{issues.length ? <div className="issue-list">{issues.map((issue, index) => <article className={`issue-row issue-row--${issue.severity.toLowerCase()}`} key={`${issue.code}-${recordId(issue.employee)}-${index}`}><div><strong>{employeeIssueLabel(issue.employee, employees)}</strong><small>{issue.severity}</small></div><span className="code-text">{issue.code}</span><p>{issue.message}</p></article>)}</div> : <div className="empty-cell">No payroll issues reported.</div>}</section>
    {delivery && <section className="panel delivery-results"><div className="section-toolbar"><div><h2>Payslip delivery</h2><p>{delivery.sent} sent · {delivery.failed} failed</p></div></div><div className="issue-list">{delivery.results.map((result, index) => <article className={`issue-row issue-row--${result.status === 'FAILED' ? 'blocking' : 'warning'}`} key={`${result.employeeId}-${index}`}><div><strong>{result.employeeCode || employeeIssueLabel(result.employeeId, employees)}</strong><small>{result.status}</small></div><p>{result.reason || 'Email sent successfully.'}</p></article>)}</div></section>}
    <section className="panel payslip-table"><div className="section-toolbar"><div><h2>Payslips ({payslips.length})</h2><p>Values are stored payroll snapshots.</p></div><Link className="button button--secondary" to={`/payroll/payslips?payrunId=${id}`}>Open Payslip List</Link></div><DataTable columns={columns} rows={payslips.map((row) => ({ ...row, id: recordId(row) }))} emptyMessage={payrun.status === 'DRAFT' ? 'Compute this Payrun to create Payslips.' : 'No Payslips available.'} /></section>
  </>
}
