import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAuth } from '../../../app/providers/authContext'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import FormField from '../../../shared/components/FormField/FormField'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import Pagination from '../../../shared/components/Pagination/Pagination'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { ROLES } from '../../../shared/constants/roles'
import { nonNegativeNumber, dateRange } from '../../../shared/validation/formValidation'
import employeesApi from '../../employees/api/employeesApi'
import { allocationsApi, timeOffTypesApi } from '../api/timeOffApi'
import { compact, employeeLabel, formatDate, recordId, referenceLabel } from '../timeOffUtils'

const blank = { employeeId: '', timeOffTypeId: '', allocatedAmount: '', validFrom: '', validUntil: '' }
export default function AllocationsPage() {
  const { user } = useAuth(); const own = user.role === ROLES.EMPLOYEE
  const [searchParams] = useSearchParams()
  const [rows, setRows] = useState([]); const [employees, setEmployees] = useState([]); const [types, setTypes] = useState([]); const [meta, setMeta] = useState(null)
  const [filters, setFilters] = useState({ employeeId: searchParams.get('employeeId') || '', timeOffTypeId: '', status: '', validOn: '', page: 1, limit: 10 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(null); const [busy, setBusy] = useState('')
  const loadRows = () => (own ? allocationsApi.mine(compact({ timeOffTypeId: filters.timeOffTypeId, status: filters.status, page: filters.page, limit: filters.limit })) : allocationsApi.list(compact(filters))).then((result) => { setRows(result.data); setMeta(result.meta) })
  useEffect(() => { let active = true; Promise.all([own ? Promise.resolve({ data: [] }) : employeesApi.list({ page: 1, limit: 100 }), timeOffTypesApi.list({}), own ? allocationsApi.mine(compact(filters)) : allocationsApi.list(compact(filters))]).then(([employeeResult, typeResult, result]) => { if (active) { setEmployees(employeeResult.data); setTypes(typeResult.data); setRows(result.data); setMeta(result.meta); setError(''); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [filters, own])
  const edit = (row) => setForm({ id: row.id, employeeId: recordId(row.employee), timeOffTypeId: recordId(row.timeOffType), allocatedAmount: row.allocatedAmount, validFrom: row.validFrom?.slice(0, 10), validUntil: row.validUntil?.slice(0, 10) })
  const submit = async (event) => { event.preventDefault(); setBusy('save'); setError(''); const amountError = nonNegativeNumber(form.allocatedAmount, 'Amount'); const dateError = dateRange(form.validFrom, form.validUntil, 'Valid from', 'Valid until', true); if (amountError || dateError) { setError(amountError || dateError); setBusy(''); return } try { const { id, ...value } = form; const payload = { ...value, allocatedAmount: Number(value.allocatedAmount) }; if (id) await allocationsApi.update(id, payload); else await allocationsApi.create(payload); setForm(null); await loadRows() } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const act = async (action, id) => { setBusy(id); setError(''); try { await allocationsApi[action](id); await loadRows() } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const columns = [...(!own ? [{ key: 'employee', label: 'Employee', render: (row) => referenceLabel(row.employee, employees, employeeLabel) }] : []), { key: 'type', label: 'Type', render: (row) => referenceLabel(row.timeOffType, types) }, { key: 'balance', label: 'Balance', render: (row) => <div><strong>{row.remainingAmount} remaining</strong><small>{row.takenAmount} taken / {row.allocatedAmount} allocated</small></div> }, { key: 'validity', label: 'Validity', render: (row) => `${formatDate(row.validFrom)} - ${formatDate(row.validUntil)}` }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, ...(!own ? [{ key: 'actions', label: '', render: (row) => <div className="row-actions">{row.status === 'DRAFT' && <><button className="button-link" onClick={() => edit(row)}>Edit</button><button className="button-link" disabled={busy === row.id} onClick={() => act('approve', row.id)}>Approve</button><button className="button-link button-link--danger" disabled={busy === row.id} onClick={() => act('remove', row.id)}>Delete</button></>}{['DRAFT', 'APPROVED'].includes(row.status) && row.takenAmount === 0 && <button className="button-link button-link--danger" disabled={busy === row.id} onClick={() => act('cancel', row.id)}>Cancel</button>}</div> }] : [])]
  const update = (name, value) => setFilters((current) => ({ ...current, [name]: value, page: 1 }))
  return <><header className="page-header"><div><p className="eyebrow">Time Off</p><h1>{own ? 'My Balances' : 'Allocations'}</h1><p>Allocated, taken, and remaining values come directly from the backend.</p></div>{!own && <button className="button" onClick={() => setForm({ ...blank })}>+ New Allocation</button>}</header><ErrorBanner message={error} />
    {!own && form && <form className="panel inline-form" onSubmit={submit}><h2>{form.id ? 'Edit Draft' : 'New'} Allocation</h2><div className="form-grid"><FormField label="Employee *"><select required value={form.employeeId} onChange={(event) => setForm({ ...form, employeeId: event.target.value })}><option value="">Select employee</option>{employees.map((employee) => <option key={recordId(employee)} value={recordId(employee)}>{employeeLabel(employee)}</option>)}</select></FormField><FormField label="Time Off Type *"><select required value={form.timeOffTypeId} onChange={(event) => setForm({ ...form, timeOffTypeId: event.target.value })}><option value="">Select type</option>{types.filter((type) => type.active || recordId(type) === form.timeOffTypeId).map((type) => <option key={recordId(type)} value={recordId(type)}>{type.name} ({type.unit})</option>)}</select></FormField><FormField label="Amount *"><input required min="0" step="0.01" type="number" value={form.allocatedAmount} onChange={(event) => setForm({ ...form, allocatedAmount: event.target.value })} /></FormField><FormField label="Valid from *"><input required type="date" value={form.validFrom} onChange={(event) => setForm({ ...form, validFrom: event.target.value })} /></FormField><FormField label="Valid until *"><input required type="date" value={form.validUntil} onChange={(event) => setForm({ ...form, validUntil: event.target.value })} /></FormField></div><div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setForm(null)}>Cancel</button><button className="button" disabled={busy === 'save'}>{busy === 'save' ? 'Saving...' : 'Save Allocation'}</button></div></form>}
    <section className="panel"><div className="operation-filters">{!own && <select value={filters.employeeId} onChange={(event) => update('employeeId', event.target.value)}><option value="">All employees</option>{employees.map((employee) => <option key={recordId(employee)} value={recordId(employee)}>{employeeLabel(employee)}</option>)}</select>}<select value={filters.timeOffTypeId} onChange={(event) => update('timeOffTypeId', event.target.value)}><option value="">All types</option>{types.map((type) => <option key={recordId(type)} value={recordId(type)}>{type.name}</option>)}</select><select value={filters.status} onChange={(event) => update('status', event.target.value)}><option value="">All statuses</option>{['DRAFT', 'APPROVED', 'CANCELLED'].map((status) => <option key={status}>{status}</option>)}</select>{!own && <input aria-label="Valid on" type="date" value={filters.validOn} onChange={(event) => update('validOn', event.target.value)} />}</div>{loading ? <LoadingState label="Loading allocations..." /> : <><DataTable columns={columns} rows={rows.map((row) => ({ ...row, id: recordId(row) }))} emptyMessage="No allocations found." /><Pagination meta={meta} onPageChange={(page) => setFilters({ ...filters, page })} /></>}</section></>
}
