import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useAuth } from '../../../app/providers/authContext'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import FormField from '../../../shared/components/FormField/FormField'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import Pagination from '../../../shared/components/Pagination/Pagination'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { ROLES } from '../../../shared/constants/roles'
import employeesApi from '../../employees/api/employeesApi'
import { allocationsApi, requestsApi, timeOffTypesApi } from '../api/timeOffApi'
import { compact, employeeLabel, formatDate, recordId, referenceLabel } from '../timeOffUtils'

const blank = { employeeId: '', timeOffTypeId: '', startDate: '', endDate: '', reason: '' }
export default function RequestsPage() {
  const { user } = useAuth(); const own = user.role === ROLES.EMPLOYEE
  const [searchParams] = useSearchParams()
  const [rows, setRows] = useState([]); const [employees, setEmployees] = useState([]); const [types, setTypes] = useState([]); const [balances, setBalances] = useState([]); const [meta, setMeta] = useState(null)
  const [filters, setFilters] = useState({ employeeId: searchParams.get('employeeId') || '', timeOffTypeId: '', status: '', from: '', to: '', page: 1, limit: 10 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState(null); const [decision, setDecision] = useState(null); const [busy, setBusy] = useState(false)
  const requestQuery = () => compact(own ? { status: filters.status, from: filters.from, to: filters.to, page: filters.page, limit: filters.limit } : filters)
  const loadRows = () => (own ? requestsApi.mine(requestQuery()) : requestsApi.list(requestQuery())).then((result) => { setRows(result.data); setMeta(result.meta) })
  const loadBalances = (employeeId = filters.employeeId) => {
    if (own) return allocationsApi.mine({ status: 'APPROVED', page: 1, limit: 100 }).then((result) => setBalances(result.data))
    if (!employeeId) { setBalances([]); return Promise.resolve() }
    return allocationsApi.list({ employeeId, status: 'APPROVED', page: 1, limit: 100 }).then((result) => setBalances(result.data))
  }
  useEffect(() => { let active = true; const query = compact(own ? { status: filters.status, from: filters.from, to: filters.to, page: filters.page, limit: filters.limit } : filters); Promise.all([own ? Promise.resolve({ data: [] }) : employeesApi.list({ page: 1, limit: 100 }), timeOffTypesApi.list({ active: true }), own ? requestsApi.mine(query) : requestsApi.list(query), own ? allocationsApi.mine({ status: 'APPROVED', page: 1, limit: 100 }) : filters.employeeId ? allocationsApi.list({ employeeId: filters.employeeId, status: 'APPROVED', page: 1, limit: 100 }) : Promise.resolve({ data: [] })]).then(([employeeResult, typeResult, requestResult, balanceResult]) => { if (active) { setEmployees(employeeResult.data); setTypes(typeResult.data); setRows(requestResult.data); setMeta(requestResult.meta); setBalances(balanceResult.data); setError(''); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [filters, own])
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const payload = own ? { timeOffTypeId: form.timeOffTypeId, startDate: form.startDate, endDate: form.endDate, reason: form.reason } : form; await requestsApi.create(payload); setForm(null); await Promise.all([loadRows(), loadBalances(form.employeeId)]) } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy(false) } }
  const decide = async (event) => { event.preventDefault(); setBusy(true); setError(''); const employeeId = recordId(decision.request.employee); try { if (decision.action === 'approve') await requestsApi.approve(decision.request.id); else await requestsApi.refuse(decision.request.id, decision.comment); setDecision(null); await Promise.all([loadRows(), loadBalances(employeeId)]) } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy(false) } }
  const columns = useMemo(() => [...(!own ? [{ key: 'employee', label: 'Employee', render: (row) => referenceLabel(row.employee, employees, employeeLabel) }] : []), { key: 'type', label: 'Type', render: (row) => referenceLabel(row.timeOffType, types) }, { key: 'dates', label: 'Dates', render: (row) => <div><strong>{formatDate(row.startDate)} - {formatDate(row.endDate)}</strong><small>{row.duration} {referenceLabel(row.timeOffType, types, (type) => type.unit?.toLowerCase())}</small></div> }, { key: 'reason', label: 'Reason' }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, ...(!own ? [{ key: 'actions', label: '', render: (row) => row.status === 'PENDING' ? <div className="row-actions"><button className="button-link" onClick={() => setDecision({ action: 'approve', request: row, comment: '' })}>Approve</button><button className="button-link button-link--danger" onClick={() => setDecision({ action: 'refuse', request: row, comment: '' })}>Refuse</button></div> : null }] : [])], [employees, own, types])
  const update = (name, value) => setFilters((current) => ({ ...current, [name]: value, page: 1 }))
  return <><header className="page-header"><div><p className="eyebrow">Time Off</p><h1>{own ? 'My Requests' : 'Time Off Requests'}</h1><p>Durations, overlap checks, approvals, and balances are calculated by the backend.</p></div><button className="button" onClick={() => setForm({ ...blank })}>+ New Request</button></header><ErrorBanner message={error} />
    {balances.length > 0 && <section className="balance-strip" aria-label="Approved leave balances">{balances.map((balance) => <div className="balance-card" key={recordId(balance)}><small>{referenceLabel(balance.timeOffType, types)}</small><strong>{balance.remainingAmount}</strong><span>of {balance.allocatedAmount} remaining</span></div>)}</section>}
    {form && <form className="panel inline-form" onSubmit={submit}><h2>New Time Off Request</h2><div className="form-grid">{!own && <FormField label="Employee *"><select required value={form.employeeId} onChange={(event) => setForm({ ...form, employeeId: event.target.value })}><option value="">Select employee</option>{employees.map((employee) => <option key={recordId(employee)} value={recordId(employee)}>{employeeLabel(employee)}</option>)}</select></FormField>}<FormField label="Time Off Type *"><select required value={form.timeOffTypeId} onChange={(event) => setForm({ ...form, timeOffTypeId: event.target.value })}><option value="">Select type</option>{types.map((type) => <option key={recordId(type)} value={recordId(type)}>{type.name} ({type.unit})</option>)}</select></FormField><FormField label="Start date *"><input required type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></FormField><FormField label="End date *"><input required type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} /></FormField><FormField label="Reason *"><textarea required rows="3" value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></FormField></div><div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setForm(null)}>Cancel</button><button className="button" disabled={busy}>{busy ? 'Submitting...' : 'Submit Request'}</button></div></form>}
    {decision && <form className="panel inline-form decision-form" onSubmit={decide}><h2>{decision.action === 'approve' ? 'Approve' : 'Refuse'} Request</h2><p>{decision.action === 'approve' ? 'The backend will re-check allocation and consume the approved balance exactly once.' : 'Refusal does not consume leave balance.'}</p>{decision.action === 'refuse' && <FormField label="Decision comment"><textarea rows="3" value={decision.comment} onChange={(event) => setDecision({ ...decision, comment: event.target.value })} /></FormField>}<div className="form-actions"><button type="button" className="button button--secondary" onClick={() => setDecision(null)}>Cancel</button><button className={`button ${decision.action === 'refuse' ? 'button--danger' : ''}`} disabled={busy}>{busy ? 'Saving...' : 'Confirm'}</button></div></form>}
    <section className="panel"><div className="operation-filters">{!own && <select value={filters.employeeId} onChange={(event) => update('employeeId', event.target.value)}><option value="">All employees</option>{employees.map((employee) => <option key={recordId(employee)} value={recordId(employee)}>{employeeLabel(employee)}</option>)}</select>}{!own && <select value={filters.timeOffTypeId} onChange={(event) => update('timeOffTypeId', event.target.value)}><option value="">All types</option>{types.map((type) => <option key={recordId(type)} value={recordId(type)}>{type.name}</option>)}</select>}<select value={filters.status} onChange={(event) => update('status', event.target.value)}><option value="">All statuses</option>{['PENDING', 'APPROVED', 'REFUSED'].map((status) => <option key={status}>{status}</option>)}</select><input aria-label="From date" type="date" value={filters.from} onChange={(event) => update('from', event.target.value)} /><input aria-label="To date" type="date" value={filters.to} onChange={(event) => update('to', event.target.value)} /></div>{loading ? <LoadingState label="Loading Time Off requests..." /> : <><DataTable columns={columns} rows={rows.map((row) => ({ ...row, id: recordId(row) }))} emptyMessage="No Time Off requests found." /><Pagination meta={meta} onPageChange={(page) => setFilters({ ...filters, page })} /></>}</section></>
}
