import { useEffect, useState } from 'react'
import { getApiError } from '../../../shared/api/apiError'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import Pagination from '../../../shared/components/Pagination/Pagination'
import notificationsApi from '../api/notificationsApi'
import { notificationId, notificationTime } from '../notificationUtils'

export default function NotificationsPage() {
  const [rows, setRows] = useState([]); const [meta, setMeta] = useState(null); const [filter, setFilter] = useState(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const load = () => notificationsApi.list({ ...(filter !== '' ? { unread: filter } : {}), page, limit: 20 }).then((result) => { setRows(result.data); setMeta(result.meta); setError('') })
  useEffect(() => { let active = true; notificationsApi.list({ ...(filter !== '' ? { unread: filter } : {}), page, limit: 20 }).then((result) => { if (active) { setRows(result.data); setMeta(result.meta); setError(''); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [filter, page])
  const read = async (id) => { setBusy(id); setError(''); try { await notificationsApi.markRead(id); await load() } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const readAll = async () => { setBusy('all'); setError(''); try { await notificationsApi.markAllRead(); await load() } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const changeFilter = (value) => { setLoading(true); setPage(1); setFilter(value) }
  return <><header className="page-header"><div><p className="eyebrow">Updates</p><h1>Notifications</h1><p>These messages are generated and owned by backend notification rules.</p></div><button className="button button--secondary" disabled={Boolean(busy)} onClick={readAll}>{busy === 'all' ? 'Updating...' : 'Mark all read'}</button></header><ErrorBanner message={error} /><section className="panel"><div className="notification-filters"><button className={!filter ? 'active' : ''} onClick={() => changeFilter('')}>All</button><button className={filter === 'true' ? 'active' : ''} onClick={() => changeFilter('true')}>Unread</button><button className={filter === 'false' ? 'active' : ''} onClick={() => changeFilter('false')}>Read</button></div>{loading ? <LoadingState label="Loading notifications..." /> : <div className="notification-list">{rows.length ? rows.map((notification) => <article className={`notification-card notification-card--${notification.severity.toLowerCase()} ${notification.readAt ? '' : 'notification-card--unread'}`} key={notificationId(notification)}><div className="notification-card-heading"><div><strong>{notification.title}</strong><span className={`notification-severity notification-severity--${notification.severity.toLowerCase()}`}>{notification.severity.replace('_', ' ')}</span></div><small>{notificationTime(notification.createdAt)}</small></div><p>{notification.message}</p><footer><span>{notification.readAt ? `Read ${notificationTime(notification.readAt)}` : 'Unread'}</span>{!notification.readAt && <button className="button-link" disabled={busy === notificationId(notification)} onClick={() => read(notificationId(notification))}>Mark read</button>}</footer></article>) : <div className="empty-cell">No notifications found.</div>}<Pagination meta={meta} onPageChange={(value) => { setLoading(true); setPage(value) }} /></div>}</section></>
}
