'use strict';

module.exports = Object.freeze({
  AUTH_INVALID_CREDENTIALS: { code: 'AUTH-001', message: 'Invalid email or password.', statusCode: 401 },
  AUTH_INVALID_TOKEN: { code: 'AUTH-002', message: 'Authentication token is missing or invalid.', statusCode: 401 },
  AUTH_FORBIDDEN: { code: 'AUTH-003', message: 'You do not have permission to perform this action.', statusCode: 403 },
  AUTH_INACTIVE: { code: 'AUTH-004', message: 'User account is inactive.', statusCode: 403 },
  AUTH_MUST_CHANGE_PASSWORD: { code: 'AUTH-005', message: 'Password change is required.', statusCode: 403 },
  USER_DUPLICATE_EMAIL: { code: 'USR-001', message: 'A user with this email already exists.', statusCode: 409 },
  USER_INVALID_ROLE: { code: 'USR-002', message: 'Role must be a canonical PeoplePay360 role.', statusCode: 400 },
  USER_INVALID_PASSWORD: { code: 'USR-003', message: 'Password does not meet the password policy.', statusCode: 400 },
  USER_PASSWORD_FORBIDDEN: { code: 'USR-004', message: 'Existing passwords cannot be retrieved.', statusCode: 403 },
  USER_DUPLICATE_BOOTSTRAP: { code: 'USR-005', message: 'A bootstrap Admin already exists.', statusCode: 409 },
  USER_EMPLOYEE_REQUIRES_ONBOARDING: {
    code: 'USR-006',
    message: 'EMPLOYEE accounts must be provisioned through Employee onboarding.',
    statusCode: 422,
  },
  CONTRACT_INVALID_DATES: { code: 'CTR-001', message: 'Contract start date must be before or equal to end date.', statusCode: 422 },
  CONTRACT_OVERLAP: { code: 'CTR-002', message: 'Multiple contracts are applicable for the selected period.', statusCode: 422 },
  CONTRACT_NOT_APPLICABLE: { code: 'CTR-003', message: 'No applicable contract exists for the selected period.', statusCode: 422 },
  CONTRACT_WAGE_MISSING: { code: 'CTR-004', message: 'Contract wage is required for wage-based payroll.', statusCode: 422 },
  CONTRACT_NEGATIVE_WAGE: { code: 'CTR-005', message: 'Contract wage cannot be negative.', statusCode: 422 },
  CONTRACT_STRUCTURE_MISSING: { code: 'CTR-006', message: 'Contract Salary Structure is required.', statusCode: 422 },
  CONTRACT_STRUCTURE_MISMATCH: { code: 'CTR-007', message: 'Contract Salary Structure does not match Payrun Salary Structure.', statusCode: 422 },
  CONTRACT_STARTS_AFTER_PERIOD: { code: 'CTR-008', message: 'Contract starts after the selected period.', statusCode: 422 },
  CONTRACT_ENDS_BEFORE_PERIOD: { code: 'CTR-009', message: 'Contract ends before the selected period.', statusCode: 422 },
  VALIDATION_ERROR: { code: 'VALIDATION_ERROR', message: 'Request validation failed.', statusCode: 400 },
  RESOURCE_NOT_FOUND: { code: 'RESOURCE_NOT_FOUND', message: 'Resource not found.', statusCode: 404 },
});
