import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../../../app/providers/authContext'
import { getApiError } from '../../../shared/api/apiError'
import ConfirmDialog from '../../../shared/components/ConfirmDialog/ConfirmDialog'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { canManageSalaryConfig } from '../../../shared/permissions/permissions'
import salaryConfigApi from '../api/salaryConfigApi'
import { recordId } from '../salaryConfigUtils'

export default function SalaryStructureDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const canManage = canManageSalaryConfig(user); const navigate = useNavigate(); const [structure, setStructure] = useState(null); const [rules, setRules] = useState([]); const [ruleCount, setRuleCount] = useState(0); const [error, setError] = useState(''); const [action, setAction] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { let active = true; Promise.all([salaryConfigApi.getStructure(id), salaryConfigApi.listRules({ salaryStructureId: id, page: 1, limit: 100 })]).then(([value, result]) => { if (active) { setStructure(value); setRules(result.data); setRuleCount(result.meta.total) } }).catch((requestError) => { if (active) setError(getApiError(requestError).message) }); return () => { active = false } }, [id])
  const run = async () => { setBusy(true); setError(''); try { if (action === 'delete') { await salaryConfigApi.deleteStructure(id); navigate('/salary-config/structures'); return } const saved = await salaryConfigApi[action === 'activate' ? 'activateStructure' : 'deactivateStructure'](id); setStructure(saved); setAction('') } catch (requestError) { setError(getApiError(requestError).message); setAction('') } finally { setBusy(false) } }
  if (!structure && !error) return <LoadingState label="Loading Salary Structure..." />
  if (!structure) return <section className="center-message"><h1>Unable to load Salary Structure</h1><p>{error}</p><Link className="button" to="/salary-config/structures">Back</Link></section>
  const columns = [{ key: 'sequence', label: 'Sequence' }, { key: 'name', label: 'Rule', render: (row) => <Link className="table-link" to={`/salary-config/rules/${row.id}`}>{row.name}</Link> }, { key: 'code', label: 'Code', render: (row) => <span className="code-text">{row.code}</span> }, { key: 'category', label: 'Category' }, { key: 'type', label: 'Calculation', render: (row) => row.calculationType }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.active ? 'ACTIVE' : 'INACTIVE'} /> }]
  return <><ErrorBanner message={error} /><header className="page-header"><div><p className="eyebrow">Salary Structure</p><h1>{structure.name}</h1><div className="badge-row"><span className="code-text">{structure.code}</span><StatusBadge value={structure.active ? 'ACTIVE' : 'INACTIVE'} /></div></div><div className="header-actions"><Link className="button button--secondary" to="/salary-config/structures">Back</Link>{canManage && <><Link className="button button--secondary" to={`/salary-config/structures/${id}/edit`}>Edit</Link><button className="button button--secondary" onClick={() => setAction(structure.active ? 'deactivate' : 'activate')}>{structure.active ? 'Deactivate' : 'Activate'}</button><button className="button button--danger" onClick={() => setAction('delete')}>Delete</button></>}</div></header><section className="panel detail-section"><h2>Description</h2><p>{structure.description || 'No description provided.'}</p></section><section className="panel salary-rule-section"><div className="section-toolbar"><div><h2>Rules ({ruleCount})</h2><p>Rules execute in ascending sequence.</p></div>{canManage && <Link className="button" to={`/salary-config/rules/new?salaryStructureId=${id}`}>+ New Rule</Link>}</div><DataTable columns={columns} rows={rules.map((rule) => ({ ...rule, id: recordId(rule) }))} emptyMessage="No Salary Rules found." /></section><ConfirmDialog open={Boolean(action)} title={`${action === 'delete' ? 'Delete' : action === 'activate' ? 'Activate' : 'Deactivate'} this Salary Structure?`} message="Referenced resources and historical configuration remain protected by the backend." confirmLabel="Confirm" danger={action !== 'activate'} busy={busy} onCancel={() => setAction('')} onConfirm={run} /></>
}
