import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useAuth } from '../../../app/providers/authContext'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import Pagination from '../../../shared/components/Pagination/Pagination'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { canManageSalaryConfig } from '../../../shared/permissions/permissions'
import salaryConfigApi from '../api/salaryConfigApi'
import { CATEGORIES, compact, recordId, structureLabel } from '../salaryConfigUtils'

export default function SalaryRuleListPage() {
  const { user } = useAuth(); const canManage = canManageSalaryConfig(user); const [searchParams] = useSearchParams(); const [structures, setStructures] = useState([]); const [rows, setRows] = useState([]); const [meta, setMeta] = useState(null); const [filters, setFilters] = useState({ salaryStructureId: searchParams.get('salaryStructureId') || '', category: '', active: '', page: 1, limit: 10 }); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { let active = true; Promise.all([salaryConfigApi.listStructures({ page: 1, limit: 100 }), salaryConfigApi.listRules(compact(filters))]).then(([structureResult, ruleResult]) => { if (active) { setStructures(structureResult.data); setRows(ruleResult.data); setMeta(ruleResult.meta); setError(''); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [filters])
  const columns = useMemo(() => [{ key: 'sequence', label: 'Sequence', render: (row) => <strong className="sequence-value">{row.sequence}</strong> }, { key: 'name', label: 'Rule', render: (row) => <Link className="table-link" to={`/salary-config/rules/${row.id}`}>{row.name}</Link> }, { key: 'code', label: 'Code', render: (row) => <span className="code-text">{row.code}</span> }, { key: 'structure', label: 'Structure', render: (row) => structureLabel(row.salaryStructure, structures) }, { key: 'category', label: 'Category' }, { key: 'type', label: 'Calculation', render: (row) => row.calculationType }, { key: 'active', label: 'Status', render: (row) => <StatusBadge value={row.active ? 'ACTIVE' : 'INACTIVE'} /> }, { key: 'actions', label: '', render: (row) => <div className="row-actions"><Link className="button-link" to={`/salary-config/rules/${row.id}`}>View</Link>{canManage && <Link className="button-link" to={`/salary-config/rules/${row.id}/edit`}>Edit</Link>}</div> }], [canManage, structures])
  return <><header className="page-header"><div><p className="eyebrow">Payroll configuration</p><h1>Salary Rules</h1><p>Rules execute in ascending sequence. All dependency validation runs on the backend.</p></div>{canManage && <Link className="button" to={`/salary-config/rules/new${filters.salaryStructureId ? `?salaryStructureId=${filters.salaryStructureId}` : ''}`}>+ New Rule</Link>}</header><ErrorBanner message={error} /><section className="panel"><div className="operation-filters"><select value={filters.salaryStructureId} onChange={(event) => setFilters({ ...filters, salaryStructureId: event.target.value, page: 1 })}><option value="">All Structures</option>{structures.map((item) => <option key={recordId(item)} value={recordId(item)}>{item.name}</option>)}</select><select value={filters.category} onChange={(event) => setFilters({ ...filters, category: event.target.value, page: 1 })}><option value="">All categories</option>{CATEGORIES.map((value) => <option key={value}>{value}</option>)}</select><select value={filters.active} onChange={(event) => setFilters({ ...filters, active: event.target.value, page: 1 })}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select></div>{loading ? <LoadingState label="Loading Salary Rules..." /> : <><DataTable columns={columns} rows={rows.map((row) => ({ ...row, id: recordId(row) }))} emptyMessage="No Salary Rules found." /><Pagination meta={meta} onPageChange={(page) => setFilters({ ...filters, page })} /></>}</section></>
}
