import { useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import Pagination from '../../../shared/components/Pagination/Pagination'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { compact, formatDate, formatMoney, recordId } from '../../payruns/payrollUiUtils'
import payslipApi, { downloadPayslipPdf } from '../api/payslipApi'

export default function PayslipListPage() {
  const [searchParams] = useSearchParams(); const [rows, setRows] = useState([]); const [meta, setMeta] = useState(null); const [filters, setFilters] = useState({ payrunId: searchParams.get('payrunId') || '', employeeId: '', status: '', from: '', to: '', page: 1, limit: 10 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('')
  useEffect(() => { let active = true; payslipApi.list(compact(filters)).then((result) => { if (active) { setRows(result.data); setMeta(result.meta); setError(''); setLoading(false) } }).catch((requestError) => { if (active) { setError(getApiError(requestError).message); setLoading(false) } }); return () => { active = false } }, [filters])
  const pdf = async (id) => { setBusy(id); setError(''); try { await downloadPayslipPdf(id) } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy('') } }
  const columns = useMemo(() => [{ key: 'employee', label: 'Employee', render: (row) => <div><strong>{row.employeeSnapshot?.name || 'Employee'}</strong><small>{row.employeeSnapshot?.employeeId}</small></div> }, { key: 'period', label: 'Period', render: (row) => `${formatDate(row.periodStart)} - ${formatDate(row.periodEnd)}` }, { key: 'worked', label: 'Worked Days', render: (row) => row.workedDays }, { key: 'gross', label: 'Gross', render: (row) => formatMoney(row.grossSalary) }, { key: 'deductions', label: 'Deductions', render: (row) => formatMoney(row.totalDeductions) }, { key: 'net', label: 'Net', render: (row) => <strong>{formatMoney(row.netSalary)}</strong> }, { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> }, { key: 'actions', label: '', render: (row) => <div className="row-actions"><Link className="button-link" to={`/payroll/payslips/${row.id}`}>View</Link>{['VALIDATED', 'PAID'].includes(row.status) && <button className="button-link" disabled={busy === row.id} onClick={() => pdf(row.id)}>PDF</button>}</div> }], [busy])
  const update = (name, value) => setFilters((current) => ({ ...current, [name]: value, page: 1 }))
  return <><header className="page-header"><div><p className="eyebrow">Payroll</p><h1>Payslips</h1><p>Review stored salary snapshots generated through Payrun computation.</p></div><Link className="button button--secondary" to="/payroll/payruns">Payruns</Link></header><ErrorBanner message={error} /><section className="panel"><div className="operation-filters"><input aria-label="Payrun ID" placeholder="Payrun ID" value={filters.payrunId} onChange={(event) => update('payrunId', event.target.value)} /><input aria-label="Employee ID" placeholder="Employee ID" value={filters.employeeId} onChange={(event) => update('employeeId', event.target.value)} /><select value={filters.status} onChange={(event) => update('status', event.target.value)}><option value="">All statuses</option>{['COMPUTED', 'VALIDATED', 'PAID'].map((status) => <option key={status}>{status}</option>)}</select><input aria-label="Period from" type="date" value={filters.from} onChange={(event) => update('from', event.target.value)} /><input aria-label="Period to" type="date" value={filters.to} onChange={(event) => update('to', event.target.value)} /></div>{loading ? <LoadingState label="Loading Payslips..." /> : <><DataTable columns={columns} rows={rows.map((row) => ({ ...row, id: recordId(row) }))} emptyMessage="No Payslips found." /><Pagination meta={meta} onPageChange={(page) => setFilters({ ...filters, page })} /></>}</section></>
}
