import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../../../app/providers/authContext'
import { getApiError } from '../../../shared/api/apiError'
import DataTable from '../../../shared/components/DataTable/DataTable'
import ErrorBanner from '../../../shared/components/ErrorBanner/ErrorBanner'
import LoadingState from '../../../shared/components/LoadingState/LoadingState'
import StatusBadge from '../../../shared/components/StatusBadge/StatusBadge'
import { ROLES } from '../../../shared/constants/roles'
import { formatDate, formatMoney, recordId } from '../../payruns/payrollUiUtils'
import payslipApi, { downloadPayslipPdf } from '../api/payslipApi'

function Total({ label, value, net }) { return <div className={`payroll-total ${net ? 'payroll-total--net' : ''}`}><span>{label}</span><strong>{formatMoney(value)}</strong></div> }
export default function PayslipDetailPage() {
  const { id } = useParams(); const { user } = useAuth(); const employeeView = user?.role === ROLES.EMPLOYEE; const [payslip, setPayslip] = useState(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  useEffect(() => { payslipApi.get(id).then(setPayslip).catch((requestError) => setError(getApiError(requestError).message)) }, [id])
  const pdf = async () => { setBusy(true); setError(''); try { await downloadPayslipPdf(id) } catch (requestError) { setError(getApiError(requestError).message) } finally { setBusy(false) } }
  if (!payslip && !error) return <LoadingState label="Loading Payslip..." />
  if (!payslip) return <section className="center-message"><h1>Unable to load Payslip</h1><p>{error}</p><Link className="button" to={employeeView ? '/my-payslips' : '/payroll/payslips'}>Back</Link></section>
  const lines = [...(payslip.salaryLines || [])].sort((a, b) => a.sequence - b.sequence).map((line, index) => ({ ...line, id: recordId(line.ruleId) || `${line.code}-${index}` }))
  const columns = [{ key: 'sequence', label: 'Sequence' }, { key: 'name', label: 'Rule Name' }, { key: 'code', label: 'Code', render: (row) => <span className="code-text">{row.code}</span> }, { key: 'category', label: 'Category' }, { key: 'amount', label: 'Amount', render: (row) => formatMoney(row.amount) }]
  return <><ErrorBanner message={error} /><header className="page-header"><div><p className="eyebrow">{payslip.payrunSummary?.name || 'Payslip'} / {payslip.employeeSnapshot?.employeeId}</p><h1>{payslip.employeeSnapshot?.name}</h1><div className="badge-row"><StatusBadge value={payslip.status} /><span>{payslip.salaryStructureSnapshot?.name}</span></div><p>{formatDate(payslip.periodStart)} - {formatDate(payslip.periodEnd)}</p></div><div className="header-actions">{!employeeView && <Link className="button button--secondary" to={`/payroll/payruns/${recordId(payslip.payrun)}`}>Payrun</Link>}<Link className="button button--secondary" to={employeeView ? '/my-payslips' : '/payroll/payslips'}>Back</Link>{['VALIDATED', 'PAID'].includes(payslip.status) && <button className="button" disabled={busy} onClick={pdf}>{busy ? 'Preparing...' : 'Download PDF'}</button>}</div></header><div className="payslip-summary"><section className="panel detail-section"><h2>Payroll context</h2><dl><div className="detail-item"><dt>Payrun</dt><dd>{payslip.payrunSummary?.name || 'Payroll'}</dd></div><div className="detail-item"><dt>Employee</dt><dd>{payslip.employeeSnapshot?.name}</dd></div><div className="detail-item"><dt>Job position</dt><dd>{payslip.employeeSnapshot?.jobPosition || payslip.contractSnapshot?.jobPosition}</dd></div><div className="detail-item"><dt>Salary Structure</dt><dd>{payslip.salaryStructureSnapshot?.name}</dd></div><div className="detail-item"><dt>Worked Days</dt><dd>{payslip.workedDays}</dd></div></dl></section><section className="panel totals-card"><Total label="Basic" value={payslip.basicSalary} /><Total label="Allowances" value={payslip.totalAllowances} /><Total label="Gross" value={payslip.grossSalary} /><Total label="Deductions" value={payslip.totalDeductions} /><Total label="Net Salary" value={payslip.netSalary} net /></section></div><section className="panel payslip-lines"><div className="section-toolbar"><div><h2>Salary computation</h2><p>Stored values from the original Payrun computation.</p></div></div><DataTable columns={columns} rows={lines} /></section><section className="panel payroll-issues"><div className="section-toolbar"><div><h2>Warnings ({payslip.warnings?.length || 0})</h2></div></div>{payslip.warnings?.length ? <div className="issue-list">{payslip.warnings.map((warning, index) => <article className={`issue-row issue-row--${warning.severity?.toLowerCase()}`} key={`${warning.code}-${index}`}><span className="code-text">{warning.code}</span><strong>{warning.severity}</strong><p>{warning.message}</p></article>)}</div> : <div className="empty-cell">No warnings.</div>}</section></>
}
